openapi: 3.0.0
servers:
  #  - url: //petstore.swagger.io/v2
  #    description: Default server
  #  - url: //petstore.swagger.io/sandbox
  #    description: Sandbox server
  - url: https://my.camps.digital
    description: Production server for subdomain *my*
info:
  version: 1.0.1
  title: CADI API Dokumentation
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://cdn.jsdelivr.net/gh/wirtschaftswunder-digital/API-Documentation@main/logo.png'
    altText: 'CADI API Logo'
externalDocs:
  description: Dokumentation für die Integration von CADI Frontend Komponenten
  url: 'https://leon-1207.github.io/CADI-Documentation/'
components:
  securitySchemes:
    CORS:
      type: apiKey
      in: header
      name: Origin
      description: Nur Anfragen von registrierten Domains werden akzeptiert.
paths:
  /api/open_v1/products/index:
    parameters:
      - name: anbieter_id
        in: query
        description: ID des Anbieters
        required: true
        schema:
          type: integer
          format: int64
          example: 1
      - name: locale
        in: query
        description: Sprache
        required: false
        schema:
          type: string
          example: en
          default: de
    get:
      tags:
        - "Öffentliche API"
      summary: "Destinationen (öffentlich)"
      description: "API zum laden der Destinationen eines Anbieters und ihrer Basisinformationen"
      responses:
        '200':
          description: "Erfolgreiche Anfrage"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                      description: ID der Destination
                    title:
                      type: string
                      description: Titel der Destination
                    saisons:
                      type: array
                      items:
                        type: string
                      description: Saisons der Destination
                      example: ["Sommer", "Herbst"]
                    min_age:
                      type: integer
                      description: Mindestalter
                    exception_min_age:
                      type: integer
                      description: Maximal erlaubte Unterschreitung des Mindestalters
                    max_age:
                      type: integer
                      description: Höchstalter
                    exception_max_age:
                      type: integer
                      description: Maximal erlaubte Überschreitung des Höchstalters
                    restrictive_age:
                      type: boolean
                      description: Gibt an ob bei der Buchung nur Teilnehmer mit einem Alter innerhalb des definierten Bereichs erlaubt werden
                    location:
                      type: string
                      description: Standort der Destination
                    img_url:
                      type: string
                      format: uri
                      description: URL des Titelbildes, welches für die Destination festgelegt wurde
                    description:
                      type: string
                      description: Beschreibung der Destination
                    product_page_url:
                      type: string
                      format: uri
                      description: URL der Produktseite
                    tags:
                      type: array
                      items:
                        type: string
                      description: Tags der Destination
                    event_count:
                      type: integer
                      description: Anzahl der Termine, die online gestellt sind
                    additional_values:
                      type: array
                      items:
                        nullable: true
                        type: string
                      description: In CADI angegebene zusätzliche Werte
                    daycamp:
                      type: boolean
                      description: Dieser Wert gibt an, ob angeben wurde, dass es sich bei der Destination um ein Daycamp handelt
              example:
                - id: 163
                  title: Actioncamp Alpensommer Zell am See 11-13 Jahre
                  saisons: ["Sommer"]
                  min_age: 11
                  exception_min_age: -1
                  max_age: 13
                  exception_max_age: 1
                  restrictive_age: null
                  location: Zell am See
                  img_url: "https://s3-eu-central-1.amazonaws.com/wwdig-images/reisebilder/bilds/000/009/046/gallery/sommerferien-jugendreise-oesterreich.jpg?1546858001"
                  description: Erlebe eine spannende Woche voller Action und Abenteur in den Bergen. Der Club Kitzsteinhorn ist das Paradies für 11-13 Jahre ★
                  product_page_url: "https://www.jugendreisen.com/jugendreisen/oesterreich/zell-am-see/163-my-actioncamp-alpensommer-zell-am-see-11-13-jahre"
                  tags: ["Action & Abenteuer"]
                  event_count: 17
                  additional_values: ["", ""]
                  daycamp: false
                - id: 239
                  title: Skifreizeit Alpenwinter Zell am See 11-13 Jahre
                  saisons: ["Winter"]
                  min_age: 11
                  exception_min_age: -1
                  max_age: 13
                  exception_max_age: 1
                  restrictive_age: null
                  location: Zell am See
                  img_url: "https://s3-eu-central-1.amazonaws.com/wwdig-images/reisebilder/bilds/000/003/545/gallery/geilste-skijugendreise.jpg?1537777276"
                  description: Zeig mal was du schon kannst - wow - kannst du das auch! Wir bleiben zusammen und erkunden gemeinsam, so sind wir mutig und stark! ♥
                  product_page_url: "https://www.jugendreisen.com/jugendreisen/oesterreich/zell-am-see/239-my-skifreizeit-alpenwinter-zell-am-see-11-13-jahre"
                  tags: ["Ski & Snow"]
                  event_count: 4
                  additional_values: [null, null]
                  daycamp: false
  /api/open_v1/events/index:
    parameters:
      - name: destination_id
        in: query
        description: ID der Destination
        required: true
        schema:
          type: integer
          format: int64
          example: 151
      - name: host_id
        in: query
        description: Host ID des Anbieters
        required: true
        schema:
          type: integer
          format: int64
          example: 57
      - name: locale
        in: query
        description: Sprache
        required: false
        schema:
          type: string
          example: en
          default: de
    get:
      description: "Termine einer Destination abrufen"
      summary: "Termine einer Destination (öffentlich)"
      security:
        - {}
      tags:
        - "Öffentliche API"
      responses:
        '200':
          description: "Erfolgreiche Anfrage"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Termin-ID die dem Kunden angezeigt wird (kann in CADI geändert werden)
                    termin_id:
                      type: integer
                      description: Interne Termin-ID (wird in der Datenbank verwendet und dem Kunden nicht angezeigt)
                    destination_id:
                      type: integer
                      description: ID der Destination
                    booking_url:
                      type: string
                      nullable: true
                      format: uri
                      description: URL zur Buchungsmaske des Termins
                    start:
                      type: string
                      format: date
                      description: Startdatum im Format dd.mm.yyyy
                    end:
                      type: string
                      format: date
                      description: Enddatum im Format dd.mm.yyyy
                    nights:
                      type: integer
                      nullable: true
                      description: Anzahl an Nächten (falls in CADI angegeben)
                    days:
                      type: integer
                      nullable: false
                      description: Anzahl an Tagen
                    price:
                      type: integer
                      nullable: false
                      description: Grundpreis für den Termin (vor Rabatt)
                    discount:
                      type: string
                      description: Rabatt für den Termin (in Euro) mit "." als Dezimaltrennzeichen
                      example: "100.0"
                      nullable: true
                    availability:
                      type: string
                      description: Verfügbarkeit an Plätzen im Termin
                      enum:
                        - "0"
                        - "<= 10"
                        - "> 10"
                    waitlist:
                      type: boolean
                      description: Dieser Wert gibt an, ob der Termin für den Termin die Warteliste aktiviert wurde
                    additional_values:
                      type: array
                      items:
                        nullable: true
                        type: string
                      description: In CADI angegebene zusätzliche Werte
              example:
                - id: "24-151-01"
                  termin_id: 29239
                  destination_id: 151
                  booking_url: "https://foxsummit.de/buchungsmaske-fox?vendor=Fox&destination_id=151&termin_id=29239&host=57&extern=true&locale=de"
                  start: "27.12.2023"
                  end: "03.01.2024"
                  nights: 5
                  days: 8
                  price: 569
                  discount: null
                  availability: "<= 10"
                  waitlist: true
                  additional_values: [null, null]
                - id: "24-151-02"
                  termin_id: 29240
                  destination_id: 151
                  booking_url: "https://foxsummit.de/buchungsmaske-fox?vendor=Fox&destination_id=151&termin_id=29240&host=57&extern=true&locale=de"
                  start: "01.01.2024"
                  end: "07.01.2024"
                  nights: 4
                  days: 7
                  price: 449
                  discount: null
                  availability: "<= 10"
                  waitlist: true
                  additional_values: [null, null]
                - id: "24-151-L1"
                  termin_id: 29241
                  destination_id: 151
                  booking_url: "https://foxsummit.de/buchungsmaske-fox?vendor=Fox&destination_id=151&termin_id=29241&host=57&extern=true&locale=de"
                  start: "27.12.2023"
                  end: "07.01.2024"
                  nights: 9
                  days: 12
                  price: 899
                  discount: null
                  availability: "0"
                  waitlist: true
                  additional_values: [null, null]
                - id: "24-151-P1"
                  termin_id: 29242
                  destination_id: 151
                  booking_url: "https://foxsummit.de/buchungsmaske-fox?vendor=Fox&destination_id=151&termin_id=29242&host=57&extern=true&locale=de"
                  start: "26.12.2023"
                  end: "02.01.2024"
                  nights: 7
                  days: 8
                  price: 1099
                  discount: null
                  availability: "0"
                  waitlist: false
                  additional_values: [null, null]
  /api/v1/reiserabatte/index?user=CORS:
    parameters:
      - name: termin_id
        in: query
        description: ID des Termins
        required: true
        schema:
          type: integer
          format: int64
          example: 29239
    get:
      description: Rabatte für einen Termin abrufen
      summary: Rabatte für einen Termin
      security:
        - CORS: []
      tags:
        - "Geschlossene API"
      responses:
        '200':
          description: "Erfolgreiche Anfrage"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: ID des Rabatts
                        type:
                          type: string
                          description: Typ des Rabatts
                        attributes:
                          type: object
                          properties:
                            startdatum:
                              type: string
                              format: date (YYYY-MM-DD)
                              nullable: true
                              description: Startdatum des Rabatts (falls vorhanden) 
                            enddatum:
                              type: string
                              format: date (YYYY-MM-DD)
                              nullable: true
                              description: Enddatum des Rabatts (falls vorhanden)
                            name:
                              type: string
                              description: Name des Rabatts
                            summe:
                              type: string
                              description: Rabattsumme (in Euro) mit "." als Dezimaltrennzeichen
                example:
                  data:
                    - id: "1724605"
                      type: "reiserabatt"
                      attributes:
                        startdatum: "2023-11-03"
                        enddatum: null
                        name: "Frühbucher"
                        summe: "50.0"