name: deploy_v2

on:
  push:
    branches:
      - main  # or specify the branch you want to trigger this on

jobs:
  redoc:
    name: Redoc CLI Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: redoc-cli-github-action
        uses: seeebiii/redoc-cli-github-action@v9
